CREATE TABLE APP_USER (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(100),
    PASSWORD VARCHAR(255),
    ROLE VARCHAR(50)
);



CREATE TABLE DOCUMENT (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    DOB DATE NOT NULL,
    TYPE VARCHAR(100) NOT NULL,
    FILE_NAME VARCHAR(255) NOT NULL,
    FILE_PATH VARCHAR(1000),
    HASH VARCHAR(255),
    AGREE BOOLEAN DEFAULT FALSE,
    UPLOADED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE resume_result (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    candidate_id VARCHAR(255),
    name VARCHAR(255),
    score DOUBLE,
    keyword_suggestions VARCHAR(2000),
    resume_path VARCHAR(1000),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DELETE FROM APP_USER;

INSERT INTO APP_USER (id, username, password, role) VALUES (
  1,
  'admin',
  '$2a$12$E7nT9DqIKi9UpKtWSJY.Oe2Q4a7f3ZYl5TI9WyeFBlGDwofAgs562',  -- ← admin123
  'ADMIN'
);
